import './layout.scss'
import Header from '@/components/base/Header/Header'
import Footer from '@/components/base/Footer/Footer'
import { Roboto } from "next/font/google";

const RobotoFont = Roboto({
  weight: "500",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={RobotoFont.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
